### ISSUE TITLE
Failed to build module 'Kindly' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug

### ISSUE THREAD

**Issue by LokeshMyXplora** [kindly-ai/sdk-chat-ios#1]
Unable to compile the project after adding Kindly into PodFile.

My IOS Project minimum deployment target is set to 13.0.

Getting multiple error for Kindly supported sdk's (SnapKit, Starscream)

![Untitled](https://github.com/kindly-ai/sdk-chat-ios/assets/71493987/8183cd1f-92c1-4b09-9ce5-3231e77dad9f)

**Comment by AlexyIbrahim** [comment]
Hi @LokeshMyXplora 

Thank you for bringing this to our attention,
We have recently removed SnapKit library from the SDK in our latest [release](https://github.com/kindly-ai/sdk-chat-ios/releases/tag/2.0.99)

To resolve this, please ensure you update to the latest version,

If you have any further questions or need additional support, feel free to ask,
